server:
  port: 8080

spring:
  application:
    name: DockerDemo
  mvc:
    async:
      request-timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.70.221:3306/dockerdemo?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.example.dockerdemo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
